# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.5
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

# конструктор формы остался у товарища,
# поэтому пришлось править вручную
# может быть источником неожиданных багов интерфейса


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(741, 584)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("train_transportation_6990.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet("background-color: #e9eaed\n"
"")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.input_station_from = QtWidgets.QLineEdit(self.centralwidget)
        self.input_station_from.setGeometry(QtCore.QRect(20, 270, 221, 41))
        self.input_station_from.setStyleSheet("font-size: 16px;\n"
"font-family: \"IBM_Plex_Sans\",\"Arial\",sans-serif;\n"
"background-color: white\n"
"")
        self.input_station_from.setInputMask("")
        self.input_station_from.setText("")
        self.input_station_from.setObjectName("input_station_from")
        self.input_station_to = QtWidgets.QLineEdit(self.centralwidget)
        self.input_station_to.setGeometry(QtCore.QRect(250, 270, 241, 41))
        self.input_station_to.setStyleSheet("font-size: 16px;\n"
"font-family: \"IBM_Plex_Sans\",\"Arial\",sans-serif;\n"
"background-color: white")
        self.input_station_to.setText("")
        self.input_station_to.setObjectName("input_station_to")
        self.input_date = QtWidgets.QLineEdit(self.centralwidget)
        self.input_date.setGeometry(QtCore.QRect(500, 270, 221, 41))
        self.input_date.setStyleSheet("font-size: 16px;\n"
"font-family: \"IBM_Plex_Sans\",\"Arial\",sans-serif;\n"
"background-color: white\n"
"")
        self.delete_last_Button = QtWidgets.QPushButton(self.centralwidget)
        self.delete_last_Button.setGeometry(QtCore.QRect(40, 350, 131, 71))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.delete_last_Button.setFont(font)
        self.delete_last_Button.setTabletTracking(False)
        self.delete_last_Button.setStyleSheet("QPushButton {\n"
"    color: white;\n"
"    border: 1px solid #111111;\n"
"    background-color: #e21a1a;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #ce2222\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #9a0b0b\n"
"}\n"
"\n"
"QPushButton:disabled {\n"
"    background-color: #c98989;\n"
"    border: 0px;\n"
"}\n"
"")
        self.delete_last_Button.setObjectName("delete_last_Button")
        self.add_Button = QtWidgets.QPushButton(self.centralwidget)
        self.add_Button.setEnabled(True)
        self.add_Button.setGeometry(QtCore.QRect(570, 350, 131, 71))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.add_Button.setFont(font)
        self.add_Button.setStyleSheet("QPushButton {\n"
"    color: white;\n"
"    border: 1px solid #111111;\n"
"    background-color: #e21a1a;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #ce2222\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #9a0b0b\n"
"}\n"
"\n"
"QPushButton:disabled {\n"
"    background-color: #c98989;\n"
"    border: 0px;\n"
"}\n"
"")
        self.add_Button.setCheckable(False)
        self.add_Button.setAutoRepeat(False)
        self.add_Button.setAutoExclusive(False)
        self.add_Button.setObjectName("add_Button")
        self.accept_Button = QtWidgets.QPushButton(self.centralwidget)
        self.accept_Button.setEnabled(True)
        self.accept_Button.setGeometry(QtCore.QRect(220, 480, 301, 81))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.accept_Button.setFont(font)
        self.accept_Button.setStyleSheet("QPushButton {\n"
"    border: 1px solid #111111;\n"
"    color: white;\n"
"    background-color: #e21a1a;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #ce2222;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #9a0b0b;\n"
"}\n"
"\n"
"QPushButton:disabled {\n"
"    background-color: #c98989;\n"
"    border: 0px;\n"
"}\n"
"")
        self.accept_Button.setObjectName("accept_Button")
        font = QtGui.QFont()
        font.setPointSize(9)
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(20, 330, 701, 131))
        self.frame.setStyleSheet("background-color: white;\n"
"")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.outputPath = QtWidgets.QTextEdit(self.centralwidget)
        self.outputPath.setGeometry(QtCore.QRect(20, 20, 691, 231))
        self.outputPath.setDocumentTitle("")
        self.outputPath.setReadOnly(True)
        self.outputPath.setPlaceholderText("")
        self.outputPath.setObjectName("outputPath")
        self.frame.raise_()
        self.input_station_from.raise_()
        self.input_station_to.raise_()
        self.input_date.raise_()
        self.delete_last_Button.raise_()
        self.add_Button.raise_()
        self.accept_Button.raise_()
        self.outputPath.raise_()
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Auto test UI"))
        self.input_station_from.setPlaceholderText(_translate("MainWindow", "Откуда"))
        self.input_station_to.setPlaceholderText(_translate("MainWindow", "Куда"))
        self.input_date.setPlaceholderText(_translate("MainWindow", "Дата отправления"))

        self.delete_last_Button.setText(_translate("MainWindow", "УДАЛИТЬ"))
        self.add_Button.setText(_translate("MainWindow", "ВСТАВИТЬ"))
        self.accept_Button.setText(_translate("MainWindow", "ПОДТВЕРДИТЬ"))

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
